RouletteBetting.Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RouletteBetting.Client.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RouletteBetting.Client/Controllers/RoulettesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using RouletteBetting.BusinessLogic;
using RouletteBetting.ViewModels;

namespace RouletteBetting.Client.Controllers
{
    public class RoulettesController : Controller
    {
        private static string baseUri = ConfigurationManager.AppSettings["WebApiUriBase"];
        private static string createRouletteUri = ConfigurationManager.AppSettings["CreateRoulette"];
        private static string getRoulettesUri = ConfigurationManager.AppSettings["GetRoulettes"];
        private static string openRouletteUri = ConfigurationManager.AppSettings["OpenRoulette"];
        private static string closeRouletteUri = ConfigurationManager.AppSettings["CloseRoulette"];
        private static string betByNumberUri = ConfigurationManager.AppSettings["MakeBetByNumber"];
        private static string betByColorUri = ConfigurationManager.AppSettings["MakeBetByColor"];

        // GET: Roulettes
        public ActionResult Index()
        {
            string uri = string.Concat(baseUri, getRoulettesUri);
            IEnumerable<RouletteViewModel> roulettes = BusinessClientWebApp.GetInstance().GetRoulettes(uri);

            return View(roulettes);
        }

        // GET: Roulettes/Create
        public ActionResult Create()
        {
            try
            {
                // TODO: Add insert logic here
                string uri = string.Concat(baseUri, createRouletteUri);
                BusinessClientWebApp.GetInstance().CreateUser(uri);
            }
            catch
            {

            }

            return RedirectToAction("Index");
        }

        // GET: Roulettes/Open/5
        public ActionResult Open(int id)
        {
            string uri = string.Concat(baseUri, openRouletteUri, "?rouletteId=" + id);
            BusinessClientWebApp.GetInstance().OpenRoulette(uri);

            return RedirectToAction("Index");
        }

        // GET: Roulettes/Bets/5
        public ActionResult Bets(int id)
        {
            string uri = string.Concat(baseUri, closeRouletteUri, "?rouletteId=" + id);
            List<GetBetViewModel> bets = BusinessClientWebApp.GetInstance().CloseRoulette(uri);
            if (bets != null && bets.Count > 0)
            {
                return View(bets);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //GET: Roulettes/MakeBetByNumber/1
        public ActionResult MakeBetByNumber(int id)
        {
            return View();
        }

        //POST: Roulettes/MakeBetByNumber/1
        [HttpPost]
        public ActionResult MakeBetByNumber(int id, FormCollection collection)
        {
            Dictionary<string, string> values = new Dictionary<string, string>
            {
                {"UserId", collection.GetValue("UserId").AttemptedValue },
                {"Money",  collection.GetValue("Money").AttemptedValue},
                {"Number",  collection.GetValue("Number").AttemptedValue}
            };
            HttpContent content = new FormUrlEncodedContent(values);
            string uri = string.Concat(baseUri, betByNumberUri);
            string result = BusinessClientWebApp.GetInstance().MakeBet(uri, content);

            return RedirectToAction("Index");
        }

        //GET: Roulettes/MakeBetByColor/1
        public ActionResult MakeBetByColor(int id)
        {
            return View();
        }

        //POST: Roulettes/MakeBetByColor/1
        [HttpPost]
        public ActionResult MakeBetByColor(int id, FormCollection collection)
        {
            Dictionary<string, string> values = new Dictionary<string, string>
            {
                {"UserId", collection.GetValue("UserId").AttemptedValue },
                {"Money",  collection.GetValue("Money").AttemptedValue},
                {"Color",  collection.GetValue("Color").AttemptedValue}
            };
            HttpContent content = new FormUrlEncodedContent(values);
            string uri = string.Concat(baseUri, betByColorUri);
            string result = BusinessClientWebApp.GetInstance().MakeBet(uri, content);

            return RedirectToAction("Index");
        }
    }
}

RouletteBetting.Client/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RouletteBetting.BusinessLogic;
using RouletteBetting.ViewModels;

namespace RouletteBetting.Client.Controllers
{
    public class UsersController : Controller
    {
        private static string baseUri = ConfigurationManager.AppSettings["WebApiUriBase"];
        private static string getUsersUri = ConfigurationManager.AppSettings["GetUsers"];
        private static string createUserUri = ConfigurationManager.AppSettings["CreateUser"];

        // GET: Users
        public ActionResult Index()
        {
            string uri = string.Concat(baseUri, getUsersUri);
            IEnumerable<UserViewModel> users = BusinessClientWebApp.GetInstance().GetUsers(uri);
            return View(users);
        }


        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                string name = collection.GetValue("UserName").AttemptedValue;
                string uri = string.Concat(baseUri, createUserUri, "?name=" + name);
                BusinessClientWebApp.GetInstance().CreateUser(uri);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RouletteBetting.Client/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RouletteBetting.Client/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RouletteBetting.Client/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RouletteBetting.Client/Views/Roulettes/Bets.cshtml
@model IEnumerable<RouletteBetting.ViewModels.GetBetViewModel>

@{
    ViewBag.Title = "Bets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bets</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BetId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RouletteId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Money)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BetId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RouletteId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Money)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RouletteBetting.Client/Views/Roulettes/Index.cshtml
@model IEnumerable<RouletteBetting.ViewModels.RouletteViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RouletteId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RouletteId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Open", "Open", new { id = item.RouletteId }, new {  })   |
                    @Html.ActionLink("Close", "Bets", new { id = item.RouletteId }, new { })   | 
                    @Html.ActionLink("Make bet by number", "MakeBetByNumber", new { id = item.RouletteId }, new { }) |
                    @Html.ActionLink("Make bet by color", "MakeBetByColor", new { id = item.RouletteId }, new {}) |
                </td>
            </tr>
        }

    </table>
}

RouletteBetting.Client/Views/Roulettes/MakeBetByColor.cshtml
@model RouletteBetting.ViewModels.BetByColorViewModel

@{
    ViewBag.Title = "MakeBetByColor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Make Bet By Color</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Bet By Color</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RouletteBetting.Client/Views/Roulettes/MakeBetByNumber.cshtml
@model RouletteBetting.ViewModels.BetByNumberViewModel

@{
    ViewBag.Title = "MakeBetByNumber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Make Bet By Number</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bet By Number</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.RouletteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RouletteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RouletteId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RouletteBetting.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Roulette Betting Web App", "Index", "Roulettes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    <li>@Html.ActionLink("Roulettes", "Index", "Roulettes")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RouletteBetting.Client/Views/Users/Create.cshtml
@model RouletteBetting.ViewModels.UserViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RouletteBetting.Client/Views/Users/Index.cshtml
@model IEnumerable<RouletteBetting.ViewModels.UserViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>

        </tr>
    }

</table>